# Generated by Django 3.0.5 on 2020-06-25 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityMarkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('grade', models.PositiveIntegerField()),
                ('out0f', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Father',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_first_name', models.CharField(max_length=255)),
                ('f_middle_name', models.CharField(max_length=255)),
                ('f_last_name', models.CharField(max_length=255)),
                ('f_pic', models.ImageField(blank=True, upload_to='')),
                ('f_ASC', models.PositiveIntegerField()),
                ('f_zoba', models.CharField(choices=[('MAEKEL', 'MAEKEL'), ('SOUTHERN', 'SOUTHERN'), ('GASH-BARKA', 'GASH-BARKA'), ('ANSEBA', 'ANSEBA'), ('NORTHERN-RED-SEA', 'NORTHERN-RED-SEA'), ('SOUTHERN-RED-SEA', 'SOUTHERN-RED-SEA')], max_length=20)),
                ('f_sub_zoba', models.CharField(blank=True, max_length=255)),
                ('f_religion', models.CharField(choices=[('CHRISTIAN', 'CHRISTIAN'), ('MUSLIM', 'MUSLIM')], max_length=10)),
                ('f_phone_no', models.IntegerField(blank=True)),
                ('f_occupation', models.CharField(blank=True, max_length=255)),
                ('f_is_guardian', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_first_name', models.CharField(max_length=255)),
                ('g_middle_name', models.CharField(max_length=255)),
                ('g_last_name', models.CharField(max_length=255)),
                ('g_guardian_pic', models.ImageField(blank=True, upload_to='')),
                ('g_ASC', models.PositiveIntegerField()),
                ('g_gender', models.CharField(choices=[('F', 'FEMALE'), ('M', 'MALE')], default='', max_length=1)),
                ('g_zoba', models.CharField(choices=[('MAEKEL', 'MAEKEL'), ('SOUTHERN', 'SOUTHERN'), ('GASH-BARKA', 'GASH-BARKA'), ('ANSEBA', 'ANSEBA'), ('NORTHERN-RED-SEA', 'NORTHERN-RED-SEA'), ('SOUTHERN-RED-SEA', 'SOUTHERN-RED-SEA')], max_length=20)),
                ('g_sub_zoba', models.CharField(max_length=255)),
                ('g_religion', models.CharField(choices=[('CHRISTIAN', 'CHRISTIAN'), ('MUSLIM', 'MUSLIM')], max_length=10)),
                ('g_phone_no', models.PositiveIntegerField(blank=True)),
                ('g_occupation', models.CharField(blank=True, max_length=255)),
                ('g_relationship', models.CharField(default='', max_length=100)),
                ('g_is_father', models.BooleanField()),
                ('g_is_mother', models.BooleanField()),
                ('g_is_guardian', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_first_name', models.CharField(max_length=255)),
                ('m_middle_name', models.CharField(max_length=255)),
                ('m_last_name', models.CharField(max_length=255)),
                ('m_mother_pic', models.ImageField(blank=True, upload_to='')),
                ('m_ASC', models.PositiveIntegerField()),
                ('m_zoba', models.CharField(choices=[('MAEKEL', 'MAEKEL'), ('SOUTHERN', 'SOUTHERN'), ('GASH-BARKA', 'GASH-BARKA'), ('ANSEBA', 'ANSEBA'), ('NORTHERN-RED-SEA', 'NORTHERN-RED-SEA'), ('SOUTHERN-RED-SEA', 'SOUTHERN-RED-SEA')], max_length=20)),
                ('m_sub_zoba', models.CharField(max_length=255)),
                ('m_religion', models.CharField(choices=[('CHRISTIAN', 'CHRISTIAN'), ('MUSLIM', 'MUSLIM')], max_length=10)),
                ('m_phone_no', models.PositiveIntegerField(blank=True)),
                ('m_occupation', models.CharField(blank=True, max_length=255)),
                ('m_is_guardian', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('student_pic', models.CharField(max_length=255)),
                ('ASC', models.IntegerField()),
                ('zoba', models.CharField(choices=[('MAEKEL', 'MAEKEL'), ('SOUTHERN', 'SOUTHERN'), ('GASH-BARKA', 'GASH-BARKA'), ('ANSEBA', 'ANSEBA'), ('NORTHERN-RED-SEA', 'NORTHERN-RED-SEA'), ('SOUTHERN-RED-SEA', 'SOUTHERN-RED-SEA')], max_length=20)),
                ('sub_zoba', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('religion', models.CharField(choices=[('CHRISTIAN', 'CHRISTIAN'), ('MUSLIM', 'MUSLIM')], max_length=10)),
                ('gender', models.CharField(choices=[('F', 'FEMALE'), ('M', 'MALE')], max_length=1)),
                ('birth_place', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('ethnicity', models.CharField(choices=[('TIGRIGNA', 'TIGRIGNA'), ('TIGRE', 'TIGRE'), ('SAHO', 'SAHO'), ('BILEN', 'BILEN'), ('AFAR', 'AFAR'), ('NARA', 'NARA'), ('KUNAMA', 'KUNAMA'), ('HIDAREB', 'HIDAREB'), ('RASHAIDA', 'RASHAIDA')], max_length=10)),
                ('DOB', models.DateField()),
                ('admission_date', models.DateField()),
                ('father_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_father', to='stumgmt.Father')),
                ('guardian_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_guardian', to='stumgmt.Guardian')),
                ('mother_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_mother', to='stumgmt.Mother')),
            ],
        ),
        migrations.CreateModel(
            name='StudentActivityMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('grade', models.PositiveIntegerField()),
                ('section', models.PositiveIntegerField()),
                ('result', models.PositiveIntegerField()),
                ('subject_teacher', models.CharField(max_length=100)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_activity', to='stumgmt.ActivityMarkType')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='stumgmt.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField()),
                ('grade', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('out_of_40', models.PositiveIntegerField()),
                ('out_of_60', models.PositiveIntegerField()),
                ('out_of_100', models.PositiveIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_activity_mark', to='stumgmt.StudentActivityMark')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTotalMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField()),
                ('grade', models.PositiveIntegerField()),
                ('section', models.PositiveIntegerField()),
                ('sub1', models.CharField(max_length=100)),
                ('sub2', models.CharField(max_length=100)),
                ('sub3', models.CharField(max_length=100)),
                ('sub4', models.CharField(max_length=100)),
                ('sub5', models.CharField(max_length=100)),
                ('sub6', models.CharField(max_length=100)),
                ('sub7', models.CharField(max_length=100)),
                ('sub8', models.CharField(max_length=100)),
                ('sub9', models.CharField(max_length=100)),
                ('total', models.PositiveIntegerField()),
                ('average', models.PositiveIntegerField()),
                ('rank', models.PositiveIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_mark', to='stumgmt.StudentMark')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField()),
                ('section', models.PositiveIntegerField()),
                ('roll_no', models.PositiveIntegerField()),
                ('stu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stu_profile', to='stumgmt.Student')),
            ],
        ),
    ]
