# Generated by Django 3.0.6 on 2020-06-28 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stumgmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentactivitymark',
            name='student_activity',
        ),
        migrations.AddField(
            model_name='studentactivitymark',
            name='student_profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='stumgmt.StudentProfile'),
        ),
        migrations.AlterField(
            model_name='studentactivitymark',
            name='mark19',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentactivitymark',
            name='mark2',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentactivitymark',
            name='mark20',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentactivitymark',
            name='mark3',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentactivitymark',
            name='mark4',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentactivitymark',
            name='mark5',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentactivitymark',
            name='mark6',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentactivitymark',
            name='mark7',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentactivitymark',
            name='mark8',
            field=models.PositiveIntegerField(),
        ),
    ]
