# Generated by Django 3.0.6 on 2020-06-28 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_auto_20200628_0945'),
        ('stumgmt', '0003_auto_20200628_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentactivitymark',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='student_subject', to='academy.Subject'),
        ),
    ]
