# Generated by Django 3.0.6 on 2020-06-28 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherassignment',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.Grade'),
        ),
        migrations.AddField(
            model_name='section',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.Grade'),
        ),
        migrations.AddField(
            model_name='section',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.Room'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('block', 'room')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'grade')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('grade', 'section')},
        ),
        migrations.AlterIndexTogether(
            name='section',
            index_together={('grade', 'section')},
        ),
    ]
