# Generated by Django 3.0.5 on 2020-06-25 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff_mgmt', '0002_employeestatus'),
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherassignment',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='staff_mgmt.EmployeeStatus'),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.Grade'),
        ),
        migrations.AddField(
            model_name='section',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.Grade'),
        ),
        migrations.AddField(
            model_name='section',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.Room'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('block', 'room')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'grade')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('grade', 'section')},
        ),
        migrations.AlterIndexTogether(
            name='section',
            index_together={('grade', 'section')},
        ),
    ]
